DROP TABLE IF EXISTS campeonatobr_serieb;

CREATE TABLE campeonatobr_serieb(
	idgameteam character varying(30),
	date date,
	time character(5),
	round integer,
	day character(3),
	tournament character varying(75),
	venue character(4),
	idteam character varying(10),
	team character varying(100),
	opponent character varying(100),
	result character(1),
	points integer,
	gf integer,
	ga integer,
	possession numeric(5,3),
	attendance integer,
	captain character varying(75),
	formation character varying(12),
	referee character varying(75),
	gdiff integer,
	shots integer,
	shotsontarget integer,
	p_shotsontarget numeric(5,3),
	goals_shots numeric(3,2),
	goals_shotsontarget numeric(3,2),
	penalty_goals integer,
	penalty_attempted integer,
	p_penaltyconverted numeric(3,2),
	shotsontarget_against integer,
	saves integer,
	p_saves numeric(5,3),
	cleansheets integer,
	penalty_attempted_against integer,
	penalty_saved integer,
	p_penalty_saved numeric(3,2),
	yellow_cards integer,
	red_cards integer,
	two_yellow_cards integer,
	fouls_commited integer,
	fouls_draw integer,
	offsides integer,
	crosses integer,
	interceptions integer,
	tackles_won integer,
	own_goals integer,
	PRIMARY KEY (idgameteam)
)
;