DROP TABLE IF EXISTS campeonatobr_serieb_modelagem;

CREATE TABLE campeonatobr_serieb_modelagem(
    idteamgame character varying(120),
    idopponentgame character varying(120),
    tournament character varying(120),
    venue character(4),
    result character(1),
    points numeric,
    possession numeric,
    gdiff numeric,
    shots numeric,
    p_shotsontarget numeric,
    goals_shots numeric,
    penalty_goals numeric,
    p_penaltyconverted numeric,
    shotsontarget_against numeric,
    p_saves numeric,
    cleansheets numeric,
    penalty_attempted_against numeric,
    p_penalty_saved numeric,
    cardscore numeric,
    foulsdiff numeric,
    offsides numeric,
    crosses numeric,
    interceptions numeric,
    tackles_won numeric,
    own_goals numeric,
    opp_points numeric,
    opp_possession numeric,
    opp_gdiff numeric,
    opp_shots numeric,
    opp_p_shotsontarget numeric,
    opp_goals_shots numeric,
    opp_penalty_goals numeric,
    opp_p_penaltyconverted numeric,
    opp_shotsontarget_against numeric,
    opp_p_saves numeric,
    opp_cleansheets numeric,
    opp_penalty_attempted_against numeric,
    opp_p_penalty_saved numeric,
    opp_cardscore numeric,
    opp_foulsdiff numeric,
    opp_offsides numeric,
    opp_crosses numeric,
    opp_interceptions numeric,
    opp_tackles_won numeric,
    opp_own_goals numeric,
    PRIMARY KEY idteamgame
)
;